language: ruby
before_install:
  - gem install bundler -v '< 2'
rvm:
  - 1.8.7
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.1
  - ruby-head
  - jruby-9.1.9.0
  - jruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  fast_finish: true
