dist: trusty
language: ruby
rvm:
  - 1.8.7-p371
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby-9.1.17.0
  - jruby-head
  - truffleruby
matrix:
  allow_failures:
  - rvm: truffleruby
  - rvm: ruby-head
  - rvm: jruby-head
  fast_finish: true
